inbound:
  name: "inbound-proxy"
  server:
    tcp:
      listenAddress: "127.0.0.1:7333"
#      tls:
#        certificatePath: ""
#        keyPath: ""
#        clientCAPath: ""
#        requireClientAuth: true
  client:
    type: "cadence"
    tcp:
      serverAddress: "127.0.0.1:7833"
      tls:
        certificatePath: ""
        keyPath: ""
        serverCAPath: ""
        serverName: ""

outbound:
  name: "outbound-proxy"
  server:
    type: "cadence"
    tcp:
      listenAddress: "127.0.0.1:7733"
      tls:
        certificatePath: ""
        keyPath: ""
        clientCAPath: ""
        requireClientAuth: true
  client:
    tcp:
      serverAddress: "127.0.0.1:7233"
      tls:
        certificatePath: ""
        keyPath: ""
        serverCAPath: ""
        serverName: ""