clusterConnections:
  - name: "b-inbound-server/b-outbound-server"
    local:
      connectionType: "tcp"
      tcpClient:
        address: "localhost:8233"
      tcpServer:
        address: "0.0.0.0:6433"
    remote:
      connectionType: "mux-server"
      muxAddressInfo:
        address: "0.0.0.0:6434"
    shardCount:
      mode: "routing"
      localShardCount: 3
      remoteShardCount: 2
    memberlist:
      enabled: true
      nodeName: "proxy-node-b-2"
      bindAddr: "127.0.0.1"
      bindPort: 6435
      joinAddrs:
        - "localhost:6335"
      proxyAddresses:
        proxy-node-b-1: "localhost:6333"
        proxy-node-b-2: "localhost:6433"
profiling:
  pprofAddress: "localhost:6071"
