clusterConnections:
  - name: "b-inbound-server/b-outbound-server"
    local:
      connectionType: "tcp"
      tcpClient:
        address: "localhost:8233"
      tcpServer:
        address: "0.0.0.0:6333"
    remote:
      connectionType: "mux-server"
      muxAddressInfo:
        address: "0.0.0.0:6334"
    customSearchAttributes:
      namespaceMappings:
        - name: "actions-b"
          # search attribute name provided by customer -> internal field name
          customSearchAttributes:
            CustomKeywordField: "Keyword03"
            CustomStringField: "Text02"
