clusterConnections:
  - name: "inbound-server"
    local:
      connectionType: "tcp"
      tcpServer:
        address: "0.0.0.0:6233"
      tcpClient:
        address: "localhost:7233"
    remote:
      connectionType: "tcp"
      tcpServer:
        address: "0.0.0.0:6234"
      tcpClient:
        address: "localhost:7234"
