inbound:
  name: "inbound-server"
  server:
    tcp:
      listenAddress: "0.0.0.0:5334"
      tls:
        certificatePath: ""
        keyPath: ""
        clientCAPath: ""
        requireClientAuth: true
  client:
    tcp:
      serverAddress: "localhost:7233"
