clusterConnections:
  - name: "a-inbound-server/a-outbound-server"
    local:
      connectionType: "tcp"
      tcpClient:
        address: "localhost:7233"
      tcpServer:
        address: "0.0.0.0:6233"
    remote:
      connectionType: "mux-client"
      muxAddressInfo:
        address: "localhost:6334"
