# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  default: standard
  settings: {}
  exclusions:
    paths:
      - common/proto122

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
