// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: temporal/s2sproxy/proxyadmin/v1/service.proto

package proxyadminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyAdminService_DescribeClusterConnections_FullMethodName = "/temporal.s2sproxy.proxyadmin.v1.ProxyAdminService/DescribeClusterConnections"
)

// ProxyAdminServiceClient is the client API for ProxyAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProxyAdminService is the s2s-proxy's admin/management API.
//
// Requests carry no routing fields.
// Use gRPC metadata to control call routing:
//
//	s2s-proxy-scope    "member" answers for the receiving member only.
//	                   "group" (default) answers for every member of the receiving group,
//	                   aggregated.
//	s2s-proxy-target   Empty answers for the receiving proxy.
//	                   Else, a cluster connection name. The call is forwarded once to
//	                   that connection's counterparty. The counterparty answers at group
//	                   scope for its own group.
//
// Metadata is not propagated to outgoing calls.
type ProxyAdminServiceClient interface {
	// DescribeClusterConnections reports a proxy and the cluster connections it has to other proxies.
	DescribeClusterConnections(ctx context.Context, in *DescribeClusterConnectionsRequest, opts ...grpc.CallOption) (*DescribeClusterConnectionsResponse, error)
}

type proxyAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyAdminServiceClient(cc grpc.ClientConnInterface) ProxyAdminServiceClient {
	return &proxyAdminServiceClient{cc}
}

func (c *proxyAdminServiceClient) DescribeClusterConnections(ctx context.Context, in *DescribeClusterConnectionsRequest, opts ...grpc.CallOption) (*DescribeClusterConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeClusterConnectionsResponse)
	err := c.cc.Invoke(ctx, ProxyAdminService_DescribeClusterConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyAdminServiceServer is the server API for ProxyAdminService service.
// All implementations must embed UnimplementedProxyAdminServiceServer
// for forward compatibility.
//
// ProxyAdminService is the s2s-proxy's admin/management API.
//
// Requests carry no routing fields.
// Use gRPC metadata to control call routing:
//
//	s2s-proxy-scope    "member" answers for the receiving member only.
//	                   "group" (default) answers for every member of the receiving group,
//	                   aggregated.
//	s2s-proxy-target   Empty answers for the receiving proxy.
//	                   Else, a cluster connection name. The call is forwarded once to
//	                   that connection's counterparty. The counterparty answers at group
//	                   scope for its own group.
//
// Metadata is not propagated to outgoing calls.
type ProxyAdminServiceServer interface {
	// DescribeClusterConnections reports a proxy and the cluster connections it has to other proxies.
	DescribeClusterConnections(context.Context, *DescribeClusterConnectionsRequest) (*DescribeClusterConnectionsResponse, error)
	mustEmbedUnimplementedProxyAdminServiceServer()
}

// UnimplementedProxyAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyAdminServiceServer struct{}

func (UnimplementedProxyAdminServiceServer) DescribeClusterConnections(context.Context, *DescribeClusterConnectionsRequest) (*DescribeClusterConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeClusterConnections not implemented")
}
func (UnimplementedProxyAdminServiceServer) mustEmbedUnimplementedProxyAdminServiceServer() {}
func (UnimplementedProxyAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeProxyAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyAdminServiceServer will
// result in compilation errors.
type UnsafeProxyAdminServiceServer interface {
	mustEmbedUnimplementedProxyAdminServiceServer()
}

func RegisterProxyAdminServiceServer(s grpc.ServiceRegistrar, srv ProxyAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedProxyAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyAdminService_ServiceDesc, srv)
}

func _ProxyAdminService_DescribeClusterConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeClusterConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServiceServer).DescribeClusterConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdminService_DescribeClusterConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServiceServer).DescribeClusterConnections(ctx, req.(*DescribeClusterConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyAdminService_ServiceDesc is the grpc.ServiceDesc for ProxyAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.s2sproxy.proxyadmin.v1.ProxyAdminService",
	HandlerType: (*ProxyAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeClusterConnections",
			Handler:    _ProxyAdminService_DescribeClusterConnections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/s2sproxy/proxyadmin/v1/service.proto",
}
