// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: temporal/s2sproxy/proxyadmin/v1/service.proto

package proxyadminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectionState is coarse for now. More values will be added.
//
//	UNSPECIFIED  No state observed. Either nobody set the field, or this API does not describe
//	             the connection, such as one that is not multiplexed.
//	CONNECTED    Every session held is connected.
//	ERROR        Anything else. None connected, some but not all, or members that disagree.
type ConnectionState int32

const (
	ConnectionState_CONNECTION_STATE_UNSPECIFIED ConnectionState = 0
	ConnectionState_CONNECTION_STATE_CONNECTED   ConnectionState = 1
	ConnectionState_CONNECTION_STATE_ERROR       ConnectionState = 2
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_CONNECTED",
		2: "CONNECTION_STATE_ERROR",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED": 0,
		"CONNECTION_STATE_CONNECTED":   1,
		"CONNECTION_STATE_ERROR":       2,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_temporal_s2sproxy_proxyadmin_v1_service_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{0}
}

type DescribeClusterConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeClusterConnectionsRequest) Reset() {
	*x = DescribeClusterConnectionsRequest{}
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeClusterConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeClusterConnectionsRequest) ProtoMessage() {}

func (x *DescribeClusterConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeClusterConnectionsRequest.ProtoReflect.Descriptor instead.
func (*DescribeClusterConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{0}
}

type DescribeClusterConnectionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClusterConnections []*ClusterConnection   `protobuf:"bytes,1,rep,name=cluster_connections,json=clusterConnections,proto3" json:"cluster_connections,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DescribeClusterConnectionsResponse) Reset() {
	*x = DescribeClusterConnectionsResponse{}
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeClusterConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeClusterConnectionsResponse) ProtoMessage() {}

func (x *DescribeClusterConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeClusterConnectionsResponse.ProtoReflect.Descriptor instead.
func (*DescribeClusterConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeClusterConnectionsResponse) GetClusterConnections() []*ClusterConnection {
	if x != nil {
		return x.ClusterConnections
	}
	return nil
}

// Member is one running proxy. Members of a group answer together at group scope.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether this row came from the member that served the response.
	Self bool `protobuf:"varint,2,opt,name=self,proto3" json:"self,omitempty"`
	// The address that was dialed. Empty for self.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// The proxy version this member is running.
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetSelf() bool {
	if x != nil {
		return x.Self
	}
	return false
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Member) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type ClusterConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The configured name of this cluster connection.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The connection state, rolled up across members.
	State ConnectionState `protobuf:"varint,2,opt,name=state,proto3,enum=temporal.s2sproxy.proxyadmin.v1.ConnectionState" json:"state,omitempty"`
	// Summed over members that report this connection.
	//
	// total is the total number of mux connections members hold now.
	// target is what the config specifies should be shared amongst all members.
	MuxSessionsConnected int32                      `protobuf:"varint,3,opt,name=mux_sessions_connected,json=muxSessionsConnected,proto3" json:"mux_sessions_connected,omitempty"`
	MuxSessionsTotal     int32                      `protobuf:"varint,4,opt,name=mux_sessions_total,json=muxSessionsTotal,proto3" json:"mux_sessions_total,omitempty"`
	MuxSessionsTarget    int32                      `protobuf:"varint,7,opt,name=mux_sessions_target,json=muxSessionsTarget,proto3" json:"mux_sessions_target,omitempty"`
	Members              []*ClusterConnectionMember `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClusterConnection) Reset() {
	*x = ClusterConnection{}
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConnection) ProtoMessage() {}

func (x *ClusterConnection) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConnection.ProtoReflect.Descriptor instead.
func (*ClusterConnection) Descriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterConnection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterConnection) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ClusterConnection) GetMuxSessionsConnected() int32 {
	if x != nil {
		return x.MuxSessionsConnected
	}
	return 0
}

func (x *ClusterConnection) GetMuxSessionsTotal() int32 {
	if x != nil {
		return x.MuxSessionsTotal
	}
	return 0
}

func (x *ClusterConnection) GetMuxSessionsTarget() int32 {
	if x != nil {
		return x.MuxSessionsTarget
	}
	return 0
}

func (x *ClusterConnection) GetMembers() []*ClusterConnectionMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// ClusterConnectionMember is one member's view of one cluster connection.
type ClusterConnectionMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member this entry came from.
	Identity *Member         `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	State    ConnectionState `protobuf:"varint,2,opt,name=state,proto3,enum=temporal.s2sproxy.proxyadmin.v1.ConnectionState" json:"state,omitempty"`
	// connected and total are what this member holds now. target is what it was configured to hold.
	MuxSessionsConnected int32 `protobuf:"varint,3,opt,name=mux_sessions_connected,json=muxSessionsConnected,proto3" json:"mux_sessions_connected,omitempty"`
	MuxSessionsTotal     int32 `protobuf:"varint,4,opt,name=mux_sessions_total,json=muxSessionsTotal,proto3" json:"mux_sessions_total,omitempty"`
	MuxSessionsTarget    int32 `protobuf:"varint,5,opt,name=mux_sessions_target,json=muxSessionsTarget,proto3" json:"mux_sessions_target,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClusterConnectionMember) Reset() {
	*x = ClusterConnectionMember{}
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConnectionMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConnectionMember) ProtoMessage() {}

func (x *ClusterConnectionMember) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConnectionMember.ProtoReflect.Descriptor instead.
func (*ClusterConnectionMember) Descriptor() ([]byte, []int) {
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterConnectionMember) GetIdentity() *Member {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClusterConnectionMember) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ClusterConnectionMember) GetMuxSessionsConnected() int32 {
	if x != nil {
		return x.MuxSessionsConnected
	}
	return 0
}

func (x *ClusterConnectionMember) GetMuxSessionsTotal() int32 {
	if x != nil {
		return x.MuxSessionsTotal
	}
	return 0
}

func (x *ClusterConnectionMember) GetMuxSessionsTarget() int32 {
	if x != nil {
		return x.MuxSessionsTarget
	}
	return 0
}

var File_temporal_s2sproxy_proxyadmin_v1_service_proto protoreflect.FileDescriptor

const file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDesc = "" +
	"\n" +
	"-temporal/s2sproxy/proxyadmin/v1/service.proto\x12\x1ftemporal.s2sproxy.proxyadmin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"!DescribeClusterConnectionsRequest\"\x89\x01\n" +
	"\"DescribeClusterConnectionsResponse\x12c\n" +
	"\x13cluster_connections\x18\x01 \x03(\v22.temporal.s2sproxy.proxyadmin.v1.ClusterConnectionR\x12clusterConnections\"\x9b\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04self\x18\x02 \x01(\bR\x04self\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\xd7\x02\n" +
	"\x11ClusterConnection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\x05state\x18\x02 \x01(\x0e20.temporal.s2sproxy.proxyadmin.v1.ConnectionStateR\x05state\x124\n" +
	"\x16mux_sessions_connected\x18\x03 \x01(\x05R\x14muxSessionsConnected\x12,\n" +
	"\x12mux_sessions_total\x18\x04 \x01(\x05R\x10muxSessionsTotal\x12.\n" +
	"\x13mux_sessions_target\x18\a \x01(\x05R\x11muxSessionsTarget\x12R\n" +
	"\amembers\x18\x06 \x03(\v28.temporal.s2sproxy.proxyadmin.v1.ClusterConnectionMemberR\amembers\"\xba\x02\n" +
	"\x17ClusterConnectionMember\x12C\n" +
	"\bidentity\x18\x01 \x01(\v2'.temporal.s2sproxy.proxyadmin.v1.MemberR\bidentity\x12F\n" +
	"\x05state\x18\x02 \x01(\x0e20.temporal.s2sproxy.proxyadmin.v1.ConnectionStateR\x05state\x124\n" +
	"\x16mux_sessions_connected\x18\x03 \x01(\x05R\x14muxSessionsConnected\x12,\n" +
	"\x12mux_sessions_total\x18\x04 \x01(\x05R\x10muxSessionsTotal\x12.\n" +
	"\x13mux_sessions_target\x18\x05 \x01(\x05R\x11muxSessionsTarget*o\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONNECTION_STATE_CONNECTED\x10\x01\x12\x1a\n" +
	"\x16CONNECTION_STATE_ERROR\x10\x022\xbb\x01\n" +
	"\x11ProxyAdminService\x12\xa5\x01\n" +
	"\x1aDescribeClusterConnections\x12B.temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsRequest\x1aC.temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsResponseB@Z>github.com/temporalio/s2s-proxy/api/proxyadmin/v1;proxyadminv1b\x06proto3"

var (
	file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescOnce sync.Once
	file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescData []byte
)

func file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescGZIP() []byte {
	file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescOnce.Do(func() {
		file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDesc), len(file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDesc)))
	})
	return file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDescData
}

var file_temporal_s2sproxy_proxyadmin_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_temporal_s2sproxy_proxyadmin_v1_service_proto_goTypes = []any{
	(ConnectionState)(0),                       // 0: temporal.s2sproxy.proxyadmin.v1.ConnectionState
	(*DescribeClusterConnectionsRequest)(nil),  // 1: temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsRequest
	(*DescribeClusterConnectionsResponse)(nil), // 2: temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsResponse
	(*Member)(nil),                             // 3: temporal.s2sproxy.proxyadmin.v1.Member
	(*ClusterConnection)(nil),                  // 4: temporal.s2sproxy.proxyadmin.v1.ClusterConnection
	(*ClusterConnectionMember)(nil),            // 5: temporal.s2sproxy.proxyadmin.v1.ClusterConnectionMember
	(*timestamppb.Timestamp)(nil),              // 6: google.protobuf.Timestamp
}
var file_temporal_s2sproxy_proxyadmin_v1_service_proto_depIdxs = []int32{
	4, // 0: temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsResponse.cluster_connections:type_name -> temporal.s2sproxy.proxyadmin.v1.ClusterConnection
	6, // 1: temporal.s2sproxy.proxyadmin.v1.Member.start_time:type_name -> google.protobuf.Timestamp
	0, // 2: temporal.s2sproxy.proxyadmin.v1.ClusterConnection.state:type_name -> temporal.s2sproxy.proxyadmin.v1.ConnectionState
	5, // 3: temporal.s2sproxy.proxyadmin.v1.ClusterConnection.members:type_name -> temporal.s2sproxy.proxyadmin.v1.ClusterConnectionMember
	3, // 4: temporal.s2sproxy.proxyadmin.v1.ClusterConnectionMember.identity:type_name -> temporal.s2sproxy.proxyadmin.v1.Member
	0, // 5: temporal.s2sproxy.proxyadmin.v1.ClusterConnectionMember.state:type_name -> temporal.s2sproxy.proxyadmin.v1.ConnectionState
	1, // 6: temporal.s2sproxy.proxyadmin.v1.ProxyAdminService.DescribeClusterConnections:input_type -> temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsRequest
	2, // 7: temporal.s2sproxy.proxyadmin.v1.ProxyAdminService.DescribeClusterConnections:output_type -> temporal.s2sproxy.proxyadmin.v1.DescribeClusterConnectionsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_temporal_s2sproxy_proxyadmin_v1_service_proto_init() }
func file_temporal_s2sproxy_proxyadmin_v1_service_proto_init() {
	if File_temporal_s2sproxy_proxyadmin_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDesc), len(file_temporal_s2sproxy_proxyadmin_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temporal_s2sproxy_proxyadmin_v1_service_proto_goTypes,
		DependencyIndexes: file_temporal_s2sproxy_proxyadmin_v1_service_proto_depIdxs,
		EnumInfos:         file_temporal_s2sproxy_proxyadmin_v1_service_proto_enumTypes,
		MessageInfos:      file_temporal_s2sproxy_proxyadmin_v1_service_proto_msgTypes,
	}.Build()
	File_temporal_s2sproxy_proxyadmin_v1_service_proto = out.File
	file_temporal_s2sproxy_proxyadmin_v1_service_proto_goTypes = nil
	file_temporal_s2sproxy_proxyadmin_v1_service_proto_depIdxs = nil
}
