// Code generated by cmd/tools/genvisitor. DO NOT EDIT.
package interceptor

import (
	"context"

	serverapiadminservice "go.temporal.io/server/api/adminservice/v1"
	serverapipersistence "go.temporal.io/server/api/persistence/v1"
	serverapireplication "go.temporal.io/server/api/replication/v1"
)

func visitAdminPayloads(ctx context.Context, vAny any, opts AdminVisitOptions) error {
	switch root := vAny.(type) {
	case *serverapiadminservice.AddTasksRequest:
		for _, item1 := range root.GetTasks() {
			if err := visitAddTasksRequestTask(ctx, opts, "AddTasksRequest/Tasks/AddTasksRequest_Task", item1); err != nil {
				return err
			}
		}
	case *serverapiadminservice.AddTasksRequest_Task:
		if err := visitAddTasksRequestTask(ctx, opts, "AddTasksRequest_Task", root); err != nil {
			return err
		}
	case *serverapiadminservice.DescribeMutableStateResponse:
		y1 := root.GetCacheMutableState()
		for _, val1 := range y1.GetActivityInfos() {
			y2 := val1.GetLastHeartbeatDetails()
			if err := visitMessage(ctx, opts, y2); err != nil {
				return err
			}
			y3 := val1.GetRetryLastFailure()
			if err := visitMessage(ctx, opts, y3); err != nil {
				return err
			}
		}
		for _, item1 := range y1.GetBufferedEvents() {
			if err := visitMessage(ctx, opts, item1); err != nil {
				return err
			}
		}
		for _, val2 := range y1.GetChasmNodes() {
			y2 := val2.GetData()
			if err := visitOpaque(opts, "DescribeMutableStateResponse/CacheMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y2.GetData()); err != nil {
				return err
			}
			y3 := val2.GetMetadata()
			switch oneof := y3.GetAttributes().(type) {
			case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
				x1 := oneof.ComponentAttributes
				for _, item2 := range x1.GetPureTasks() {
					y4 := item2.GetData()
					if err := visitOpaque(opts, "DescribeMutableStateResponse/CacheMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
						return err
					}
				}
				for _, item3 := range x1.GetSideEffectTasks() {
					y4 := item3.GetData()
					if err := visitOpaque(opts, "DescribeMutableStateResponse/CacheMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
						return err
					}
				}
				y4 := x1.GetUserMetadata()
				if err := visitMessage(ctx, opts, y4); err != nil {
					return err
				}
			}
		}
		y2 := y1.GetExecutionInfo()
		for _, val3 := range y2.GetMemo() {
			if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
				return err
			}
		}
		for _, val4 := range y2.GetSearchAttributes() {
			if !opts.Payloads.SkipSearchAttributes {
				if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
					return err
				}
			}
		}
		for _, item2 := range y2.GetStateMachineTimers() {
			for _, item3 := range item2.GetInfos() {
				y3 := item3.GetData()
				if err := visitOpaque(opts, "DescribeMutableStateResponse/CacheMutableState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y3); err != nil {
					return err
				}
			}
		}
		for _, val5 := range y2.GetSubStateMachinesByType() {
			for _, val6 := range val5.GetMachinesById() {
				if err := visitStateMachineNode(ctx, opts, "DescribeMutableStateResponse/CacheMutableState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
					return err
				}
			}
		}
		y3 := root.GetDatabaseMutableState()
		for _, val1 := range y3.GetActivityInfos() {
			y4 := val1.GetLastHeartbeatDetails()
			if err := visitMessage(ctx, opts, y4); err != nil {
				return err
			}
			y5 := val1.GetRetryLastFailure()
			if err := visitMessage(ctx, opts, y5); err != nil {
				return err
			}
		}
		for _, item1 := range y3.GetBufferedEvents() {
			if err := visitMessage(ctx, opts, item1); err != nil {
				return err
			}
		}
		for _, val2 := range y3.GetChasmNodes() {
			y4 := val2.GetData()
			if err := visitOpaque(opts, "DescribeMutableStateResponse/DatabaseMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y4.GetData()); err != nil {
				return err
			}
			y5 := val2.GetMetadata()
			switch oneof := y5.GetAttributes().(type) {
			case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
				x1 := oneof.ComponentAttributes
				for _, item2 := range x1.GetPureTasks() {
					y6 := item2.GetData()
					if err := visitOpaque(opts, "DescribeMutableStateResponse/DatabaseMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y6.GetData()); err != nil {
						return err
					}
				}
				for _, item3 := range x1.GetSideEffectTasks() {
					y6 := item3.GetData()
					if err := visitOpaque(opts, "DescribeMutableStateResponse/DatabaseMutableState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y6.GetData()); err != nil {
						return err
					}
				}
				y6 := x1.GetUserMetadata()
				if err := visitMessage(ctx, opts, y6); err != nil {
					return err
				}
			}
		}
		y4 := y3.GetExecutionInfo()
		for _, val3 := range y4.GetMemo() {
			if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
				return err
			}
		}
		for _, val4 := range y4.GetSearchAttributes() {
			if !opts.Payloads.SkipSearchAttributes {
				if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
					return err
				}
			}
		}
		for _, item2 := range y4.GetStateMachineTimers() {
			for _, item3 := range item2.GetInfos() {
				y5 := item3.GetData()
				if err := visitOpaque(opts, "DescribeMutableStateResponse/DatabaseMutableState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y5); err != nil {
					return err
				}
			}
		}
		for _, val5 := range y4.GetSubStateMachinesByType() {
			for _, val6 := range val5.GetMachinesById() {
				if err := visitStateMachineNode(ctx, opts, "DescribeMutableStateResponse/DatabaseMutableState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
					return err
				}
			}
		}
	case *serverapiadminservice.GetDLQMessagesResponse:
		for _, item1 := range root.GetReplicationTasks() {
			switch oneof := item1.GetAttributes().(type) {
			case *serverapireplication.ReplicationTask_BackfillHistoryTaskAttributes:
				x1 := oneof.BackfillHistoryTaskAttributes
				for _, item2 := range x1.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y1 := x1.GetNewRunInfo()
				y2 := y1.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_HistoryTaskAttributes:
				x1 := oneof.HistoryTaskAttributes
				y1 := x1.GetEvents()
				if err := visitEventBlob(ctx, opts, y1); err != nil {
					return err
				}
				for _, item2 := range x1.GetEventsBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y2 := x1.GetNewRunEvents()
				if err := visitEventBlob(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncActivityTaskAttributes:
				x1 := oneof.SyncActivityTaskAttributes
				y1 := x1.GetDetails()
				if err := visitMessage(ctx, opts, y1); err != nil {
					return err
				}
				y2 := x1.GetLastFailure()
				if err := visitMessage(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncHsmAttributes:
				x1 := oneof.SyncHsmAttributes
				y1 := x1.GetStateMachineNode()
				if err := visitStateMachineNode(ctx, opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncHsmAttributes/SyncHSMAttributes/StateMachineNode/StateMachineNode", y1); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncVersionedTransitionTaskAttributes:
				x1 := oneof.SyncVersionedTransitionTaskAttributes
				y1 := x1.GetVersionedTransitionArtifact()
				for _, item2 := range y1.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y2 := y1.GetNewRunInfo()
				y3 := y2.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y3); err != nil {
					return err
				}
				switch oneof := y1.GetStateAttributes().(type) {
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
					x2 := oneof.SyncWorkflowStateMutationAttributes
					y4 := x2.GetStateMutation()
					y5 := y4.GetExecutionInfo()
					for _, val1 := range y5.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val1); err != nil {
							return err
						}
					}
					for _, val2 := range y5.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y5.GetStateMachineTimers() {
						for _, item4 := range item3.GetInfos() {
							y6 := item4.GetData()
							if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
								return err
							}
						}
					}
					for _, val3 := range y5.GetSubStateMachinesByType() {
						for _, val4 := range val3.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val4); err != nil {
								return err
							}
						}
					}
					for _, val1 := range y4.GetUpdatedActivityInfos() {
						y6 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y6); err != nil {
							return err
						}
						y7 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y7); err != nil {
							return err
						}
					}
					for _, val2 := range y4.GetUpdatedChasmNodes() {
						y6 := val2.GetData()
						if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
							return err
						}
						y7 := val2.GetMetadata()
						switch oneof := y7.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item3 := range x3.GetPureTasks() {
								y8 := item3.GetData()
								if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							for _, item4 := range x3.GetSideEffectTasks() {
								y8 := item4.GetData()
								if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							y8 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y8); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y4.GetUpdatedSubStateMachines() {
						y6 := item3.GetData()
						if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y6); err != nil {
							return err
						}
					}
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
					x2 := oneof.SyncWorkflowStateSnapshotAttributes
					y4 := x2.GetState()
					for _, val1 := range y4.GetActivityInfos() {
						y5 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y5); err != nil {
							return err
						}
						y6 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y6); err != nil {
							return err
						}
					}
					for _, item3 := range y4.GetBufferedEvents() {
						if err := visitMessage(ctx, opts, item3); err != nil {
							return err
						}
					}
					for _, val2 := range y4.GetChasmNodes() {
						y5 := val2.GetData()
						if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y5.GetData()); err != nil {
							return err
						}
						y6 := val2.GetMetadata()
						switch oneof := y6.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item4 := range x3.GetPureTasks() {
								y7 := item4.GetData()
								if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
									return err
								}
							}
							for _, item5 := range x3.GetSideEffectTasks() {
								y7 := item5.GetData()
								if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
									return err
								}
							}
							y7 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y7); err != nil {
								return err
							}
						}
					}
					y5 := y4.GetExecutionInfo()
					for _, val3 := range y5.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
							return err
						}
					}
					for _, val4 := range y5.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
								return err
							}
						}
					}
					for _, item4 := range y5.GetStateMachineTimers() {
						for _, item5 := range item4.GetInfos() {
							y6 := item5.GetData()
							if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
								return err
							}
						}
					}
					for _, val5 := range y5.GetSubStateMachinesByType() {
						for _, val6 := range val5.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
								return err
							}
						}
					}
				}
			case *serverapireplication.ReplicationTask_SyncWorkflowStateTaskAttributes:
				x1 := oneof.SyncWorkflowStateTaskAttributes
				y1 := x1.GetWorkflowState()
				for _, val1 := range y1.GetActivityInfos() {
					y2 := val1.GetLastHeartbeatDetails()
					if err := visitMessage(ctx, opts, y2); err != nil {
						return err
					}
					y3 := val1.GetRetryLastFailure()
					if err := visitMessage(ctx, opts, y3); err != nil {
						return err
					}
				}
				for _, item2 := range y1.GetBufferedEvents() {
					if err := visitMessage(ctx, opts, item2); err != nil {
						return err
					}
				}
				for _, val2 := range y1.GetChasmNodes() {
					y2 := val2.GetData()
					if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y2.GetData()); err != nil {
						return err
					}
					y3 := val2.GetMetadata()
					switch oneof := y3.GetAttributes().(type) {
					case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
						x2 := oneof.ComponentAttributes
						for _, item3 := range x2.GetPureTasks() {
							y4 := item3.GetData()
							if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
								return err
							}
						}
						for _, item4 := range x2.GetSideEffectTasks() {
							y4 := item4.GetData()
							if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
								return err
							}
						}
						y4 := x2.GetUserMetadata()
						if err := visitMessage(ctx, opts, y4); err != nil {
							return err
						}
					}
				}
				y2 := y1.GetExecutionInfo()
				for _, val3 := range y2.GetMemo() {
					if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
						return err
					}
				}
				for _, val4 := range y2.GetSearchAttributes() {
					if !opts.Payloads.SkipSearchAttributes {
						if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
							return err
						}
					}
				}
				for _, item3 := range y2.GetStateMachineTimers() {
					for _, item4 := range item3.GetInfos() {
						y3 := item4.GetData()
						if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y3); err != nil {
							return err
						}
					}
				}
				for _, val5 := range y2.GetSubStateMachinesByType() {
					for _, val6 := range val5.GetMachinesById() {
						if err := visitStateMachineNode(ctx, opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
							return err
						}
					}
				}
			}
			y1 := item1.GetData()
			if err := visitOpaque(opts, "GetDLQMessagesResponse/ReplicationTasks/ReplicationTask/Data", y1.GetData()); err != nil {
				return err
			}
		}
	case *serverapiadminservice.GetDLQReplicationMessagesResponse:
		for _, item1 := range root.GetReplicationTasks() {
			switch oneof := item1.GetAttributes().(type) {
			case *serverapireplication.ReplicationTask_BackfillHistoryTaskAttributes:
				x1 := oneof.BackfillHistoryTaskAttributes
				for _, item2 := range x1.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y1 := x1.GetNewRunInfo()
				y2 := y1.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_HistoryTaskAttributes:
				x1 := oneof.HistoryTaskAttributes
				y1 := x1.GetEvents()
				if err := visitEventBlob(ctx, opts, y1); err != nil {
					return err
				}
				for _, item2 := range x1.GetEventsBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y2 := x1.GetNewRunEvents()
				if err := visitEventBlob(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncActivityTaskAttributes:
				x1 := oneof.SyncActivityTaskAttributes
				y1 := x1.GetDetails()
				if err := visitMessage(ctx, opts, y1); err != nil {
					return err
				}
				y2 := x1.GetLastFailure()
				if err := visitMessage(ctx, opts, y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncHsmAttributes:
				x1 := oneof.SyncHsmAttributes
				y1 := x1.GetStateMachineNode()
				if err := visitStateMachineNode(ctx, opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncHsmAttributes/SyncHSMAttributes/StateMachineNode/StateMachineNode", y1); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncVersionedTransitionTaskAttributes:
				x1 := oneof.SyncVersionedTransitionTaskAttributes
				y1 := x1.GetVersionedTransitionArtifact()
				for _, item2 := range y1.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y2 := y1.GetNewRunInfo()
				y3 := y2.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y3); err != nil {
					return err
				}
				switch oneof := y1.GetStateAttributes().(type) {
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
					x2 := oneof.SyncWorkflowStateMutationAttributes
					y4 := x2.GetStateMutation()
					y5 := y4.GetExecutionInfo()
					for _, val1 := range y5.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val1); err != nil {
							return err
						}
					}
					for _, val2 := range y5.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y5.GetStateMachineTimers() {
						for _, item4 := range item3.GetInfos() {
							y6 := item4.GetData()
							if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
								return err
							}
						}
					}
					for _, val3 := range y5.GetSubStateMachinesByType() {
						for _, val4 := range val3.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val4); err != nil {
								return err
							}
						}
					}
					for _, val1 := range y4.GetUpdatedActivityInfos() {
						y6 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y6); err != nil {
							return err
						}
						y7 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y7); err != nil {
							return err
						}
					}
					for _, val2 := range y4.GetUpdatedChasmNodes() {
						y6 := val2.GetData()
						if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
							return err
						}
						y7 := val2.GetMetadata()
						switch oneof := y7.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item3 := range x3.GetPureTasks() {
								y8 := item3.GetData()
								if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							for _, item4 := range x3.GetSideEffectTasks() {
								y8 := item4.GetData()
								if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							y8 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y8); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y4.GetUpdatedSubStateMachines() {
						y6 := item3.GetData()
						if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y6); err != nil {
							return err
						}
					}
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
					x2 := oneof.SyncWorkflowStateSnapshotAttributes
					y4 := x2.GetState()
					for _, val1 := range y4.GetActivityInfos() {
						y5 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y5); err != nil {
							return err
						}
						y6 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y6); err != nil {
							return err
						}
					}
					for _, item3 := range y4.GetBufferedEvents() {
						if err := visitMessage(ctx, opts, item3); err != nil {
							return err
						}
					}
					for _, val2 := range y4.GetChasmNodes() {
						y5 := val2.GetData()
						if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y5.GetData()); err != nil {
							return err
						}
						y6 := val2.GetMetadata()
						switch oneof := y6.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item4 := range x3.GetPureTasks() {
								y7 := item4.GetData()
								if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
									return err
								}
							}
							for _, item5 := range x3.GetSideEffectTasks() {
								y7 := item5.GetData()
								if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
									return err
								}
							}
							y7 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y7); err != nil {
								return err
							}
						}
					}
					y5 := y4.GetExecutionInfo()
					for _, val3 := range y5.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
							return err
						}
					}
					for _, val4 := range y5.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
								return err
							}
						}
					}
					for _, item4 := range y5.GetStateMachineTimers() {
						for _, item5 := range item4.GetInfos() {
							y6 := item5.GetData()
							if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
								return err
							}
						}
					}
					for _, val5 := range y5.GetSubStateMachinesByType() {
						for _, val6 := range val5.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
								return err
							}
						}
					}
				}
			case *serverapireplication.ReplicationTask_SyncWorkflowStateTaskAttributes:
				x1 := oneof.SyncWorkflowStateTaskAttributes
				y1 := x1.GetWorkflowState()
				for _, val1 := range y1.GetActivityInfos() {
					y2 := val1.GetLastHeartbeatDetails()
					if err := visitMessage(ctx, opts, y2); err != nil {
						return err
					}
					y3 := val1.GetRetryLastFailure()
					if err := visitMessage(ctx, opts, y3); err != nil {
						return err
					}
				}
				for _, item2 := range y1.GetBufferedEvents() {
					if err := visitMessage(ctx, opts, item2); err != nil {
						return err
					}
				}
				for _, val2 := range y1.GetChasmNodes() {
					y2 := val2.GetData()
					if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y2.GetData()); err != nil {
						return err
					}
					y3 := val2.GetMetadata()
					switch oneof := y3.GetAttributes().(type) {
					case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
						x2 := oneof.ComponentAttributes
						for _, item3 := range x2.GetPureTasks() {
							y4 := item3.GetData()
							if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
								return err
							}
						}
						for _, item4 := range x2.GetSideEffectTasks() {
							y4 := item4.GetData()
							if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
								return err
							}
						}
						y4 := x2.GetUserMetadata()
						if err := visitMessage(ctx, opts, y4); err != nil {
							return err
						}
					}
				}
				y2 := y1.GetExecutionInfo()
				for _, val3 := range y2.GetMemo() {
					if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
						return err
					}
				}
				for _, val4 := range y2.GetSearchAttributes() {
					if !opts.Payloads.SkipSearchAttributes {
						if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
							return err
						}
					}
				}
				for _, item3 := range y2.GetStateMachineTimers() {
					for _, item4 := range item3.GetInfos() {
						y3 := item4.GetData()
						if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y3); err != nil {
							return err
						}
					}
				}
				for _, val5 := range y2.GetSubStateMachinesByType() {
					for _, val6 := range val5.GetMachinesById() {
						if err := visitStateMachineNode(ctx, opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
							return err
						}
					}
				}
			}
			y1 := item1.GetData()
			if err := visitOpaque(opts, "GetDLQReplicationMessagesResponse/ReplicationTasks/ReplicationTask/Data", y1.GetData()); err != nil {
				return err
			}
		}
	case *serverapiadminservice.GetDLQTasksResponse:
		for _, item1 := range root.GetDlqTasks() {
			y1 := item1.GetPayload()
			y2 := y1.GetBlob()
			if err := visitOpaque(opts, "GetDLQTasksResponse/DlqTasks/HistoryDLQTask/Payload/HistoryTask/Blob", y2.GetData()); err != nil {
				return err
			}
		}
	case *serverapiadminservice.GetNamespaceReplicationMessagesResponse:
		y1 := root.GetMessages()
		for _, item1 := range y1.GetReplicationTasks() {
			switch oneof := item1.GetAttributes().(type) {
			case *serverapireplication.ReplicationTask_BackfillHistoryTaskAttributes:
				x1 := oneof.BackfillHistoryTaskAttributes
				for _, item2 := range x1.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y2 := x1.GetNewRunInfo()
				y3 := y2.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y3); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_HistoryTaskAttributes:
				x1 := oneof.HistoryTaskAttributes
				y2 := x1.GetEvents()
				if err := visitEventBlob(ctx, opts, y2); err != nil {
					return err
				}
				for _, item2 := range x1.GetEventsBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y3 := x1.GetNewRunEvents()
				if err := visitEventBlob(ctx, opts, y3); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncActivityTaskAttributes:
				x1 := oneof.SyncActivityTaskAttributes
				y2 := x1.GetDetails()
				if err := visitMessage(ctx, opts, y2); err != nil {
					return err
				}
				y3 := x1.GetLastFailure()
				if err := visitMessage(ctx, opts, y3); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncHsmAttributes:
				x1 := oneof.SyncHsmAttributes
				y2 := x1.GetStateMachineNode()
				if err := visitStateMachineNode(ctx, opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncHsmAttributes/SyncHSMAttributes/StateMachineNode/StateMachineNode", y2); err != nil {
					return err
				}
			case *serverapireplication.ReplicationTask_SyncVersionedTransitionTaskAttributes:
				x1 := oneof.SyncVersionedTransitionTaskAttributes
				y2 := x1.GetVersionedTransitionArtifact()
				for _, item2 := range y2.GetEventBatches() {
					if err := visitEventBlob(ctx, opts, item2); err != nil {
						return err
					}
				}
				y3 := y2.GetNewRunInfo()
				y4 := y3.GetEventBatch()
				if err := visitEventBlob(ctx, opts, y4); err != nil {
					return err
				}
				switch oneof := y2.GetStateAttributes().(type) {
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
					x2 := oneof.SyncWorkflowStateMutationAttributes
					y5 := x2.GetStateMutation()
					y6 := y5.GetExecutionInfo()
					for _, val1 := range y6.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val1); err != nil {
							return err
						}
					}
					for _, val2 := range y6.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y6.GetStateMachineTimers() {
						for _, item4 := range item3.GetInfos() {
							y7 := item4.GetData()
							if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y7); err != nil {
								return err
							}
						}
					}
					for _, val3 := range y6.GetSubStateMachinesByType() {
						for _, val4 := range val3.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val4); err != nil {
								return err
							}
						}
					}
					for _, val1 := range y5.GetUpdatedActivityInfos() {
						y7 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y7); err != nil {
							return err
						}
						y8 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y8); err != nil {
							return err
						}
					}
					for _, val2 := range y5.GetUpdatedChasmNodes() {
						y7 := val2.GetData()
						if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y7.GetData()); err != nil {
							return err
						}
						y8 := val2.GetMetadata()
						switch oneof := y8.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item3 := range x3.GetPureTasks() {
								y9 := item3.GetData()
								if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y9.GetData()); err != nil {
									return err
								}
							}
							for _, item4 := range x3.GetSideEffectTasks() {
								y9 := item4.GetData()
								if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y9.GetData()); err != nil {
									return err
								}
							}
							y9 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y9); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y5.GetUpdatedSubStateMachines() {
						y7 := item3.GetData()
						if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y7); err != nil {
							return err
						}
					}
				case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
					x2 := oneof.SyncWorkflowStateSnapshotAttributes
					y5 := x2.GetState()
					for _, val1 := range y5.GetActivityInfos() {
						y6 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y6); err != nil {
							return err
						}
						y7 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y7); err != nil {
							return err
						}
					}
					for _, item3 := range y5.GetBufferedEvents() {
						if err := visitMessage(ctx, opts, item3); err != nil {
							return err
						}
					}
					for _, val2 := range y5.GetChasmNodes() {
						y6 := val2.GetData()
						if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
							return err
						}
						y7 := val2.GetMetadata()
						switch oneof := y7.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item4 := range x3.GetPureTasks() {
								y8 := item4.GetData()
								if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							for _, item5 := range x3.GetSideEffectTasks() {
								y8 := item5.GetData()
								if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
									return err
								}
							}
							y8 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y8); err != nil {
								return err
							}
						}
					}
					y6 := y5.GetExecutionInfo()
					for _, val3 := range y6.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
							return err
						}
					}
					for _, val4 := range y6.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
								return err
							}
						}
					}
					for _, item4 := range y6.GetStateMachineTimers() {
						for _, item5 := range item4.GetInfos() {
							y7 := item5.GetData()
							if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y7); err != nil {
								return err
							}
						}
					}
					for _, val5 := range y6.GetSubStateMachinesByType() {
						for _, val6 := range val5.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
								return err
							}
						}
					}
				}
			case *serverapireplication.ReplicationTask_SyncWorkflowStateTaskAttributes:
				x1 := oneof.SyncWorkflowStateTaskAttributes
				y2 := x1.GetWorkflowState()
				for _, val1 := range y2.GetActivityInfos() {
					y3 := val1.GetLastHeartbeatDetails()
					if err := visitMessage(ctx, opts, y3); err != nil {
						return err
					}
					y4 := val1.GetRetryLastFailure()
					if err := visitMessage(ctx, opts, y4); err != nil {
						return err
					}
				}
				for _, item2 := range y2.GetBufferedEvents() {
					if err := visitMessage(ctx, opts, item2); err != nil {
						return err
					}
				}
				for _, val2 := range y2.GetChasmNodes() {
					y3 := val2.GetData()
					if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y3.GetData()); err != nil {
						return err
					}
					y4 := val2.GetMetadata()
					switch oneof := y4.GetAttributes().(type) {
					case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
						x2 := oneof.ComponentAttributes
						for _, item3 := range x2.GetPureTasks() {
							y5 := item3.GetData()
							if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y5.GetData()); err != nil {
								return err
							}
						}
						for _, item4 := range x2.GetSideEffectTasks() {
							y5 := item4.GetData()
							if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y5.GetData()); err != nil {
								return err
							}
						}
						y5 := x2.GetUserMetadata()
						if err := visitMessage(ctx, opts, y5); err != nil {
							return err
						}
					}
				}
				y3 := y2.GetExecutionInfo()
				for _, val3 := range y3.GetMemo() {
					if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
						return err
					}
				}
				for _, val4 := range y3.GetSearchAttributes() {
					if !opts.Payloads.SkipSearchAttributes {
						if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
							return err
						}
					}
				}
				for _, item3 := range y3.GetStateMachineTimers() {
					for _, item4 := range item3.GetInfos() {
						y4 := item4.GetData()
						if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y4); err != nil {
							return err
						}
					}
				}
				for _, val5 := range y3.GetSubStateMachinesByType() {
					for _, val6 := range val5.GetMachinesById() {
						if err := visitStateMachineNode(ctx, opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
							return err
						}
					}
				}
			}
			y2 := item1.GetData()
			if err := visitOpaque(opts, "GetNamespaceReplicationMessagesResponse/Messages/ReplicationMessages/ReplicationTasks/ReplicationTask/Data", y2.GetData()); err != nil {
				return err
			}
		}
	case *serverapiadminservice.GetReplicationMessagesResponse:
		for _, val1 := range root.GetShardMessages() {
			for _, item1 := range val1.GetReplicationTasks() {
				switch oneof := item1.GetAttributes().(type) {
				case *serverapireplication.ReplicationTask_BackfillHistoryTaskAttributes:
					x1 := oneof.BackfillHistoryTaskAttributes
					for _, item2 := range x1.GetEventBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y1 := x1.GetNewRunInfo()
					y2 := y1.GetEventBatch()
					if err := visitEventBlob(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_HistoryTaskAttributes:
					x1 := oneof.HistoryTaskAttributes
					y1 := x1.GetEvents()
					if err := visitEventBlob(ctx, opts, y1); err != nil {
						return err
					}
					for _, item2 := range x1.GetEventsBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y2 := x1.GetNewRunEvents()
					if err := visitEventBlob(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncActivityTaskAttributes:
					x1 := oneof.SyncActivityTaskAttributes
					y1 := x1.GetDetails()
					if err := visitMessage(ctx, opts, y1); err != nil {
						return err
					}
					y2 := x1.GetLastFailure()
					if err := visitMessage(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncHsmAttributes:
					x1 := oneof.SyncHsmAttributes
					y1 := x1.GetStateMachineNode()
					if err := visitStateMachineNode(ctx, opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncHsmAttributes/SyncHSMAttributes/StateMachineNode/StateMachineNode", y1); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncVersionedTransitionTaskAttributes:
					x1 := oneof.SyncVersionedTransitionTaskAttributes
					y1 := x1.GetVersionedTransitionArtifact()
					for _, item2 := range y1.GetEventBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y2 := y1.GetNewRunInfo()
					y3 := y2.GetEventBatch()
					if err := visitEventBlob(ctx, opts, y3); err != nil {
						return err
					}
					switch oneof := y1.GetStateAttributes().(type) {
					case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
						x2 := oneof.SyncWorkflowStateMutationAttributes
						y4 := x2.GetStateMutation()
						y5 := y4.GetExecutionInfo()
						for _, val2 := range y5.GetMemo() {
							if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
								return err
							}
						}
						for _, val3 := range y5.GetSearchAttributes() {
							if !opts.Payloads.SkipSearchAttributes {
								if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
									return err
								}
							}
						}
						for _, item3 := range y5.GetStateMachineTimers() {
							for _, item4 := range item3.GetInfos() {
								y6 := item4.GetData()
								if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
									return err
								}
							}
						}
						for _, val4 := range y5.GetSubStateMachinesByType() {
							for _, val5 := range val4.GetMachinesById() {
								if err := visitStateMachineNode(ctx, opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val5); err != nil {
									return err
								}
							}
						}
						for _, val2 := range y4.GetUpdatedActivityInfos() {
							y6 := val2.GetLastHeartbeatDetails()
							if err := visitMessage(ctx, opts, y6); err != nil {
								return err
							}
							y7 := val2.GetRetryLastFailure()
							if err := visitMessage(ctx, opts, y7); err != nil {
								return err
							}
						}
						for _, val3 := range y4.GetUpdatedChasmNodes() {
							y6 := val3.GetData()
							if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
								return err
							}
							y7 := val3.GetMetadata()
							switch oneof := y7.GetAttributes().(type) {
							case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
								x3 := oneof.ComponentAttributes
								for _, item3 := range x3.GetPureTasks() {
									y8 := item3.GetData()
									if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
										return err
									}
								}
								for _, item4 := range x3.GetSideEffectTasks() {
									y8 := item4.GetData()
									if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
										return err
									}
								}
								y8 := x3.GetUserMetadata()
								if err := visitMessage(ctx, opts, y8); err != nil {
									return err
								}
							}
						}
						for _, item3 := range y4.GetUpdatedSubStateMachines() {
							y6 := item3.GetData()
							if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y6); err != nil {
								return err
							}
						}
					case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
						x2 := oneof.SyncWorkflowStateSnapshotAttributes
						y4 := x2.GetState()
						for _, val2 := range y4.GetActivityInfos() {
							y5 := val2.GetLastHeartbeatDetails()
							if err := visitMessage(ctx, opts, y5); err != nil {
								return err
							}
							y6 := val2.GetRetryLastFailure()
							if err := visitMessage(ctx, opts, y6); err != nil {
								return err
							}
						}
						for _, item3 := range y4.GetBufferedEvents() {
							if err := visitMessage(ctx, opts, item3); err != nil {
								return err
							}
						}
						for _, val3 := range y4.GetChasmNodes() {
							y5 := val3.GetData()
							if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y5.GetData()); err != nil {
								return err
							}
							y6 := val3.GetMetadata()
							switch oneof := y6.GetAttributes().(type) {
							case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
								x3 := oneof.ComponentAttributes
								for _, item4 := range x3.GetPureTasks() {
									y7 := item4.GetData()
									if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
										return err
									}
								}
								for _, item5 := range x3.GetSideEffectTasks() {
									y7 := item5.GetData()
									if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
										return err
									}
								}
								y7 := x3.GetUserMetadata()
								if err := visitMessage(ctx, opts, y7); err != nil {
									return err
								}
							}
						}
						y5 := y4.GetExecutionInfo()
						for _, val4 := range y5.GetMemo() {
							if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
								return err
							}
						}
						for _, val5 := range y5.GetSearchAttributes() {
							if !opts.Payloads.SkipSearchAttributes {
								if err := visitPayloadInPlace(ctx, opts, val5); err != nil {
									return err
								}
							}
						}
						for _, item4 := range y5.GetStateMachineTimers() {
							for _, item5 := range item4.GetInfos() {
								y6 := item5.GetData()
								if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
									return err
								}
							}
						}
						for _, val6 := range y5.GetSubStateMachinesByType() {
							for _, val7 := range val6.GetMachinesById() {
								if err := visitStateMachineNode(ctx, opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val7); err != nil {
									return err
								}
							}
						}
					}
				case *serverapireplication.ReplicationTask_SyncWorkflowStateTaskAttributes:
					x1 := oneof.SyncWorkflowStateTaskAttributes
					y1 := x1.GetWorkflowState()
					for _, val2 := range y1.GetActivityInfos() {
						y2 := val2.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y2); err != nil {
							return err
						}
						y3 := val2.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y3); err != nil {
							return err
						}
					}
					for _, item2 := range y1.GetBufferedEvents() {
						if err := visitMessage(ctx, opts, item2); err != nil {
							return err
						}
					}
					for _, val3 := range y1.GetChasmNodes() {
						y2 := val3.GetData()
						if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y2.GetData()); err != nil {
							return err
						}
						y3 := val3.GetMetadata()
						switch oneof := y3.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x2 := oneof.ComponentAttributes
							for _, item3 := range x2.GetPureTasks() {
								y4 := item3.GetData()
								if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
									return err
								}
							}
							for _, item4 := range x2.GetSideEffectTasks() {
								y4 := item4.GetData()
								if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
									return err
								}
							}
							y4 := x2.GetUserMetadata()
							if err := visitMessage(ctx, opts, y4); err != nil {
								return err
							}
						}
					}
					y2 := y1.GetExecutionInfo()
					for _, val4 := range y2.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
							return err
						}
					}
					for _, val5 := range y2.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val5); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y2.GetStateMachineTimers() {
						for _, item4 := range item3.GetInfos() {
							y3 := item4.GetData()
							if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y3); err != nil {
								return err
							}
						}
					}
					for _, val6 := range y2.GetSubStateMachinesByType() {
						for _, val7 := range val6.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val7); err != nil {
								return err
							}
						}
					}
				}
				y1 := item1.GetData()
				if err := visitOpaque(opts, "GetReplicationMessagesResponse/ShardMessages/ReplicationMessages/ReplicationTasks/ReplicationTask/Data", y1.GetData()); err != nil {
					return err
				}
			}
		}
	case *serverapiadminservice.GetSearchAttributesResponse:
		y1 := root.GetAddWorkflowExecutionInfo()
		if err := visitMessage(ctx, opts, y1); err != nil {
			return err
		}
	case *serverapiadminservice.GetWorkflowExecutionRawHistoryResponse:
		for _, item1 := range root.GetHistoryBatches() {
			if err := visitEventBlob(ctx, opts, item1); err != nil {
				return err
			}
		}
	case *serverapiadminservice.GetWorkflowExecutionRawHistoryV2Response:
		for _, item1 := range root.GetHistoryBatches() {
			if err := visitEventBlob(ctx, opts, item1); err != nil {
				return err
			}
		}
	case *serverapiadminservice.ImportWorkflowExecutionRequest:
		for _, item1 := range root.GetHistoryBatches() {
			if err := visitEventBlob(ctx, opts, item1); err != nil {
				return err
			}
		}
		y1 := root.GetToken()
		if err := visitOpaque(opts, "ImportWorkflowExecutionRequest/Token", y1); err != nil {
			return err
		}
	case *serverapiadminservice.ImportWorkflowExecutionResponse:
		y1 := root.GetToken()
		if err := visitOpaque(opts, "ImportWorkflowExecutionResponse/Token", y1); err != nil {
			return err
		}
	case *serverapiadminservice.ReapplyEventsRequest:
		y1 := root.GetEvents()
		if err := visitEventBlob(ctx, opts, y1); err != nil {
			return err
		}
	case *serverapiadminservice.StreamWorkflowReplicationMessagesResponse:
		switch oneof := root.GetAttributes().(type) {
		case *serverapiadminservice.StreamWorkflowReplicationMessagesResponse_Messages:
			x1 := oneof.Messages
			for _, item1 := range x1.GetReplicationTasks() {
				switch oneof := item1.GetAttributes().(type) {
				case *serverapireplication.ReplicationTask_BackfillHistoryTaskAttributes:
					x2 := oneof.BackfillHistoryTaskAttributes
					for _, item2 := range x2.GetEventBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y1 := x2.GetNewRunInfo()
					y2 := y1.GetEventBatch()
					if err := visitEventBlob(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_HistoryTaskAttributes:
					x2 := oneof.HistoryTaskAttributes
					y1 := x2.GetEvents()
					if err := visitEventBlob(ctx, opts, y1); err != nil {
						return err
					}
					for _, item2 := range x2.GetEventsBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y2 := x2.GetNewRunEvents()
					if err := visitEventBlob(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncActivityTaskAttributes:
					x2 := oneof.SyncActivityTaskAttributes
					y1 := x2.GetDetails()
					if err := visitMessage(ctx, opts, y1); err != nil {
						return err
					}
					y2 := x2.GetLastFailure()
					if err := visitMessage(ctx, opts, y2); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncHsmAttributes:
					x2 := oneof.SyncHsmAttributes
					y1 := x2.GetStateMachineNode()
					if err := visitStateMachineNode(ctx, opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncHsmAttributes/SyncHSMAttributes/StateMachineNode/StateMachineNode", y1); err != nil {
						return err
					}
				case *serverapireplication.ReplicationTask_SyncVersionedTransitionTaskAttributes:
					x2 := oneof.SyncVersionedTransitionTaskAttributes
					y1 := x2.GetVersionedTransitionArtifact()
					for _, item2 := range y1.GetEventBatches() {
						if err := visitEventBlob(ctx, opts, item2); err != nil {
							return err
						}
					}
					y2 := y1.GetNewRunInfo()
					y3 := y2.GetEventBatch()
					if err := visitEventBlob(ctx, opts, y3); err != nil {
						return err
					}
					switch oneof := y1.GetStateAttributes().(type) {
					case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
						x3 := oneof.SyncWorkflowStateMutationAttributes
						y4 := x3.GetStateMutation()
						y5 := y4.GetExecutionInfo()
						for _, val1 := range y5.GetMemo() {
							if err := visitPayloadInPlace(ctx, opts, val1); err != nil {
								return err
							}
						}
						for _, val2 := range y5.GetSearchAttributes() {
							if !opts.Payloads.SkipSearchAttributes {
								if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
									return err
								}
							}
						}
						for _, item3 := range y5.GetStateMachineTimers() {
							for _, item4 := range item3.GetInfos() {
								y6 := item4.GetData()
								if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
									return err
								}
							}
						}
						for _, val3 := range y5.GetSubStateMachinesByType() {
							for _, val4 := range val3.GetMachinesById() {
								if err := visitStateMachineNode(ctx, opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val4); err != nil {
									return err
								}
							}
						}
						for _, val1 := range y4.GetUpdatedActivityInfos() {
							y6 := val1.GetLastHeartbeatDetails()
							if err := visitMessage(ctx, opts, y6); err != nil {
								return err
							}
							y7 := val1.GetRetryLastFailure()
							if err := visitMessage(ctx, opts, y7); err != nil {
								return err
							}
						}
						for _, val2 := range y4.GetUpdatedChasmNodes() {
							y6 := val2.GetData()
							if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
								return err
							}
							y7 := val2.GetMetadata()
							switch oneof := y7.GetAttributes().(type) {
							case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
								x4 := oneof.ComponentAttributes
								for _, item3 := range x4.GetPureTasks() {
									y8 := item3.GetData()
									if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
										return err
									}
								}
								for _, item4 := range x4.GetSideEffectTasks() {
									y8 := item4.GetData()
									if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
										return err
									}
								}
								y8 := x4.GetUserMetadata()
								if err := visitMessage(ctx, opts, y8); err != nil {
									return err
								}
							}
						}
						for _, item3 := range y4.GetUpdatedSubStateMachines() {
							y6 := item3.GetData()
							if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y6); err != nil {
								return err
							}
						}
					case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
						x3 := oneof.SyncWorkflowStateSnapshotAttributes
						y4 := x3.GetState()
						for _, val1 := range y4.GetActivityInfos() {
							y5 := val1.GetLastHeartbeatDetails()
							if err := visitMessage(ctx, opts, y5); err != nil {
								return err
							}
							y6 := val1.GetRetryLastFailure()
							if err := visitMessage(ctx, opts, y6); err != nil {
								return err
							}
						}
						for _, item3 := range y4.GetBufferedEvents() {
							if err := visitMessage(ctx, opts, item3); err != nil {
								return err
							}
						}
						for _, val2 := range y4.GetChasmNodes() {
							y5 := val2.GetData()
							if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y5.GetData()); err != nil {
								return err
							}
							y6 := val2.GetMetadata()
							switch oneof := y6.GetAttributes().(type) {
							case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
								x4 := oneof.ComponentAttributes
								for _, item4 := range x4.GetPureTasks() {
									y7 := item4.GetData()
									if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
										return err
									}
								}
								for _, item5 := range x4.GetSideEffectTasks() {
									y7 := item5.GetData()
									if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
										return err
									}
								}
								y7 := x4.GetUserMetadata()
								if err := visitMessage(ctx, opts, y7); err != nil {
									return err
								}
							}
						}
						y5 := y4.GetExecutionInfo()
						for _, val3 := range y5.GetMemo() {
							if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
								return err
							}
						}
						for _, val4 := range y5.GetSearchAttributes() {
							if !opts.Payloads.SkipSearchAttributes {
								if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
									return err
								}
							}
						}
						for _, item4 := range y5.GetStateMachineTimers() {
							for _, item5 := range item4.GetInfos() {
								y6 := item5.GetData()
								if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
									return err
								}
							}
						}
						for _, val5 := range y5.GetSubStateMachinesByType() {
							for _, val6 := range val5.GetMachinesById() {
								if err := visitStateMachineNode(ctx, opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncVersionedTransitionTaskAttributes/SyncVersionedTransitionTaskAttributes/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
									return err
								}
							}
						}
					}
				case *serverapireplication.ReplicationTask_SyncWorkflowStateTaskAttributes:
					x2 := oneof.SyncWorkflowStateTaskAttributes
					y1 := x2.GetWorkflowState()
					for _, val1 := range y1.GetActivityInfos() {
						y2 := val1.GetLastHeartbeatDetails()
						if err := visitMessage(ctx, opts, y2); err != nil {
							return err
						}
						y3 := val1.GetRetryLastFailure()
						if err := visitMessage(ctx, opts, y3); err != nil {
							return err
						}
					}
					for _, item2 := range y1.GetBufferedEvents() {
						if err := visitMessage(ctx, opts, item2); err != nil {
							return err
						}
					}
					for _, val2 := range y1.GetChasmNodes() {
						y2 := val2.GetData()
						if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y2.GetData()); err != nil {
							return err
						}
						y3 := val2.GetMetadata()
						switch oneof := y3.GetAttributes().(type) {
						case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
							x3 := oneof.ComponentAttributes
							for _, item3 := range x3.GetPureTasks() {
								y4 := item3.GetData()
								if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
									return err
								}
							}
							for _, item4 := range x3.GetSideEffectTasks() {
								y4 := item4.GetData()
								if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y4.GetData()); err != nil {
									return err
								}
							}
							y4 := x3.GetUserMetadata()
							if err := visitMessage(ctx, opts, y4); err != nil {
								return err
							}
						}
					}
					y2 := y1.GetExecutionInfo()
					for _, val3 := range y2.GetMemo() {
						if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
							return err
						}
					}
					for _, val4 := range y2.GetSearchAttributes() {
						if !opts.Payloads.SkipSearchAttributes {
							if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
								return err
							}
						}
					}
					for _, item3 := range y2.GetStateMachineTimers() {
						for _, item4 := range item3.GetInfos() {
							y3 := item4.GetData()
							if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y3); err != nil {
								return err
							}
						}
					}
					for _, val5 := range y2.GetSubStateMachinesByType() {
						for _, val6 := range val5.GetMachinesById() {
							if err := visitStateMachineNode(ctx, opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Attributes/SyncWorkflowStateTaskAttributes/SyncWorkflowStateTaskAttributes/WorkflowState/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
								return err
							}
						}
					}
				}
				y1 := item1.GetData()
				if err := visitOpaque(opts, "StreamWorkflowReplicationMessagesResponse/Attributes/Messages/WorkflowReplicationMessages/ReplicationTasks/ReplicationTask/Data", y1.GetData()); err != nil {
					return err
				}
			}
		}
	case *serverapiadminservice.SyncWorkflowStateResponse:
		y1 := root.GetVersionedTransitionArtifact()
		for _, item1 := range y1.GetEventBatches() {
			if err := visitEventBlob(ctx, opts, item1); err != nil {
				return err
			}
		}
		y2 := y1.GetNewRunInfo()
		y3 := y2.GetEventBatch()
		if err := visitEventBlob(ctx, opts, y3); err != nil {
			return err
		}
		switch oneof := y1.GetStateAttributes().(type) {
		case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateMutationAttributes:
			x1 := oneof.SyncWorkflowStateMutationAttributes
			y4 := x1.GetStateMutation()
			y5 := y4.GetExecutionInfo()
			for _, val1 := range y5.GetMemo() {
				if err := visitPayloadInPlace(ctx, opts, val1); err != nil {
					return err
				}
			}
			for _, val2 := range y5.GetSearchAttributes() {
				if !opts.Payloads.SkipSearchAttributes {
					if err := visitPayloadInPlace(ctx, opts, val2); err != nil {
						return err
					}
				}
			}
			for _, item2 := range y5.GetStateMachineTimers() {
				for _, item3 := range item2.GetInfos() {
					y6 := item3.GetData()
					if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
						return err
					}
				}
			}
			for _, val3 := range y5.GetSubStateMachinesByType() {
				for _, val4 := range val3.GetMachinesById() {
					if err := visitStateMachineNode(ctx, opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val4); err != nil {
						return err
					}
				}
			}
			for _, val1 := range y4.GetUpdatedActivityInfos() {
				y6 := val1.GetLastHeartbeatDetails()
				if err := visitMessage(ctx, opts, y6); err != nil {
					return err
				}
				y7 := val1.GetRetryLastFailure()
				if err := visitMessage(ctx, opts, y7); err != nil {
					return err
				}
			}
			for _, val2 := range y4.GetUpdatedChasmNodes() {
				y6 := val2.GetData()
				if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Data", y6.GetData()); err != nil {
					return err
				}
				y7 := val2.GetMetadata()
				switch oneof := y7.GetAttributes().(type) {
				case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
					x2 := oneof.ComponentAttributes
					for _, item2 := range x2.GetPureTasks() {
						y8 := item2.GetData()
						if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
							return err
						}
					}
					for _, item3 := range x2.GetSideEffectTasks() {
						y8 := item3.GetData()
						if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y8.GetData()); err != nil {
							return err
						}
					}
					y8 := x2.GetUserMetadata()
					if err := visitMessage(ctx, opts, y8); err != nil {
						return err
					}
				}
			}
			for _, item2 := range y4.GetUpdatedSubStateMachines() {
				y6 := item2.GetData()
				if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateMutationAttributes/SyncWorkflowStateMutationAttributes/StateMutation/WorkflowMutableStateMutation/UpdatedSubStateMachines/WorkflowMutableStateMutation_StateMachineNodeMutation/Data", y6); err != nil {
					return err
				}
			}
		case *serverapireplication.VersionedTransitionArtifact_SyncWorkflowStateSnapshotAttributes:
			x1 := oneof.SyncWorkflowStateSnapshotAttributes
			y4 := x1.GetState()
			for _, val1 := range y4.GetActivityInfos() {
				y5 := val1.GetLastHeartbeatDetails()
				if err := visitMessage(ctx, opts, y5); err != nil {
					return err
				}
				y6 := val1.GetRetryLastFailure()
				if err := visitMessage(ctx, opts, y6); err != nil {
					return err
				}
			}
			for _, item2 := range y4.GetBufferedEvents() {
				if err := visitMessage(ctx, opts, item2); err != nil {
					return err
				}
			}
			for _, val2 := range y4.GetChasmNodes() {
				y5 := val2.GetData()
				if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Data", y5.GetData()); err != nil {
					return err
				}
				y6 := val2.GetMetadata()
				switch oneof := y6.GetAttributes().(type) {
				case *serverapipersistence.ChasmNodeMetadata_ComponentAttributes:
					x2 := oneof.ComponentAttributes
					for _, item3 := range x2.GetPureTasks() {
						y7 := item3.GetData()
						if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/PureTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
							return err
						}
					}
					for _, item4 := range x2.GetSideEffectTasks() {
						y7 := item4.GetData()
						if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ChasmNodes/ChasmNode/Metadata/ChasmNodeMetadata/Attributes/ComponentAttributes/ChasmComponentAttributes/SideEffectTasks/ChasmComponentAttributes_Task/Data", y7.GetData()); err != nil {
							return err
						}
					}
					y7 := x2.GetUserMetadata()
					if err := visitMessage(ctx, opts, y7); err != nil {
						return err
					}
				}
			}
			y5 := y4.GetExecutionInfo()
			for _, val3 := range y5.GetMemo() {
				if err := visitPayloadInPlace(ctx, opts, val3); err != nil {
					return err
				}
			}
			for _, val4 := range y5.GetSearchAttributes() {
				if !opts.Payloads.SkipSearchAttributes {
					if err := visitPayloadInPlace(ctx, opts, val4); err != nil {
						return err
					}
				}
			}
			for _, item3 := range y5.GetStateMachineTimers() {
				for _, item4 := range item3.GetInfos() {
					y6 := item4.GetData()
					if err := visitOpaque(opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/StateMachineTimers/StateMachineTimerGroup/Infos/StateMachineTaskInfo/Data", y6); err != nil {
						return err
					}
				}
			}
			for _, val5 := range y5.GetSubStateMachinesByType() {
				for _, val6 := range val5.GetMachinesById() {
					if err := visitStateMachineNode(ctx, opts, "SyncWorkflowStateResponse/VersionedTransitionArtifact/VersionedTransitionArtifact/StateAttributes/SyncWorkflowStateSnapshotAttributes/SyncWorkflowStateSnapshotAttributes/State/WorkflowMutableState/ExecutionInfo/WorkflowExecutionInfo/SubStateMachinesByType/StateMachineMap/MachinesById/StateMachineNode", val6); err != nil {
						return err
					}
				}
			}
		}
	case *serverapipersistence.OutboundTaskInfo:
		switch oneof := root.GetTaskDetails().(type) {
		case *serverapipersistence.OutboundTaskInfo_ChasmTaskInfo:
			x1 := oneof.ChasmTaskInfo
			y1 := x1.GetData()
			if err := visitOpaque(opts, "OutboundTaskInfo/TaskDetails/ChasmTaskInfo/ChasmTaskInfo/Data", y1.GetData()); err != nil {
				return err
			}
		case *serverapipersistence.OutboundTaskInfo_StateMachineInfo:
			x1 := oneof.StateMachineInfo
			y1 := x1.GetData()
			if err := visitOpaque(opts, "OutboundTaskInfo/TaskDetails/StateMachineInfo/StateMachineTaskInfo/Data", y1); err != nil {
				return err
			}
		}
	case *serverapipersistence.TimerTaskInfo:
		switch oneof := root.GetTaskDetails().(type) {
		case *serverapipersistence.TimerTaskInfo_ChasmTaskInfo:
			x1 := oneof.ChasmTaskInfo
			y1 := x1.GetData()
			if err := visitOpaque(opts, "TimerTaskInfo/TaskDetails/ChasmTaskInfo/ChasmTaskInfo/Data", y1.GetData()); err != nil {
				return err
			}
		}
	case *serverapipersistence.TransferTaskInfo:
		switch oneof := root.GetTaskDetails().(type) {
		case *serverapipersistence.TransferTaskInfo_ChasmTaskInfo:
			x1 := oneof.ChasmTaskInfo
			y1 := x1.GetData()
			if err := visitOpaque(opts, "TransferTaskInfo/TaskDetails/ChasmTaskInfo/ChasmTaskInfo/Data", y1.GetData()); err != nil {
				return err
			}
		}
	case *serverapipersistence.VisibilityTaskInfo:
		switch oneof := root.GetTaskDetails().(type) {
		case *serverapipersistence.VisibilityTaskInfo_ChasmTaskInfo:
			x1 := oneof.ChasmTaskInfo
			y1 := x1.GetData()
			if err := visitOpaque(opts, "VisibilityTaskInfo/TaskDetails/ChasmTaskInfo/ChasmTaskInfo/Data", y1.GetData()); err != nil {
				return err
			}
		}
	}
	return nil
}
