x-volumes: &x-volumes
  - ./..:/etc/develop:ro

services:
  temporal-a:
    image: temporalio/temporal:1.5.0
    command:
      - server
      - start-dev
      - --port
      - "${TEMPORAL_INTERNAL_PORT}"
      - --ip
      - "0.0.0.0"
      - --ui-port
      - "${TEMPORAL_UI_INTERNAL_PORT}"
      - --namespace
      - default
      - --log-level
      - warn
    ports:
      - "${TEMPORAL_A_EXTERNAL_PORT}:${TEMPORAL_INTERNAL_PORT}"
      - "${TEMPORAL_A_UI_EXTERNAL_PORT}:${TEMPORAL_UI_INTERNAL_PORT}"
    networks:
      - develop
    healthcheck:
      test:
        - CMD
        - temporal
        - operator
        - cluster
        - health
        - --address
        - "localhost:${TEMPORAL_INTERNAL_PORT}"
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s

  temporal-b:
    image: temporalio/temporal:1.5.0
    command:
      - server
      - start-dev
      - --port
      - "${TEMPORAL_INTERNAL_PORT}"
      - --ip
      - "0.0.0.0"
      - --ui-port
      - "${TEMPORAL_UI_INTERNAL_PORT}"
      - --namespace
      - default
      - --log-level
      - warn
    ports:
      - "${TEMPORAL_B_EXTERNAL_PORT}:${TEMPORAL_INTERNAL_PORT}"
      - "${TEMPORAL_B_UI_EXTERNAL_PORT}:${TEMPORAL_UI_INTERNAL_PORT}"
    networks:
      - develop
    healthcheck:
      test:
        - CMD
        - temporal
        - operator
        - cluster
        - health
        - --address
        - "localhost:${TEMPORAL_INTERNAL_PORT}"
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s

  proxy-b:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      CONFIG_YML: /etc/develop/docker-compose/tmp/develop.proxy-b.yaml
    volumes: *x-volumes
    ports:
      - "${PROXY_B_EXTERNAL_PORT}:${PROXY_B_INTERNAL_PORT}"
      - "${PROXY_B_METRICS_EXTERNAL_PORT}:${PROXY_METRICS_INTERNAL_PORT}"
    networks:
      - develop
    depends_on:
      temporal-b:
        condition: service_healthy
    healthcheck: # TODO: Replace with healthcheck endpoint.
      test:
        - CMD-SHELL
        - "wget -q -O /dev/null -T 3 http://localhost:${PROXY_PPROF_INTERNAL_PORT}/debug/pprof/ || exit 1"
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  proxy-a:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      CONFIG_YML: /etc/develop/docker-compose/tmp/develop.proxy-a.yaml
    volumes: *x-volumes
    ports:
      - "${PROXY_A_EXTERNAL_PORT}:${PROXY_A_INTERNAL_PORT}"
      - "${PROXY_A_METRICS_EXTERNAL_PORT}:${PROXY_METRICS_INTERNAL_PORT}"
    networks:
      - develop
    depends_on:
      temporal-a:
        condition: service_healthy
      proxy-b:
        condition: service_healthy
    healthcheck: # TODO: Replace with healthcheck endpoint.
      test:
        - CMD-SHELL
        - "wget -q -O /dev/null -T 3 http://localhost:${PROXY_PPROF_INTERNAL_PORT}/debug/pprof/ || exit 1"
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/develop/docker-compose/tmp/develop.prometheus.yaml
    volumes: *x-volumes
    ports:
      - "${PROMETHEUS_EXTERNAL_PORT}:${PROMETHEUS_INTERNAL_PORT}"
    networks:
      - develop
    depends_on:
      proxy-a:
        condition: service_healthy
      proxy-b:
        condition: service_healthy

  smoke-test:
    image: temporalio/temporal:1.5.0
    entrypoint: /bin/sh
    networks:
      - develop
    depends_on:
      proxy-a:
        condition: service_healthy
      proxy-b:
        condition: service_healthy
    volumes: *x-volumes
    environment:
      TEMPORAL_A_INBOUND: "temporal-a:${TEMPORAL_INTERNAL_PORT}"
      TEMPORAL_B_INBOUND: "temporal-b:${TEMPORAL_INTERNAL_PORT}"
      PROXY_A_OUTBOUND: "proxy-a:${PROXY_A_INTERNAL_PORT}"
      PROXY_B_OUTBOUND: "proxy-b:${PROXY_B_INTERNAL_PORT}"
    command:
      - /etc/develop/docker-compose/smoke-test.sh

networks:
  develop:
    driver: bridge
