clusterConnections:
  - name: "cluster-a"
    local:
      connectionType: "tcp"
      tcpClient:
        address: "temporal-a:${TEMPORAL_INTERNAL_PORT}"
      tcpServer:
        address: "0.0.0.0:${PROXY_A_INTERNAL_PORT}"
    remote:
      connectionType: "mux-client"
      muxCount: 1
      muxAddressInfo:
        address: "proxy-b:${PROXY_MUX_INTERNAL_PORT}"
profiling:
  pprofAddress: "0.0.0.0:${PROXY_PPROF_INTERNAL_PORT}"
metrics:
  prometheus:
    listenAddress: "0.0.0.0:${PROXY_METRICS_INTERNAL_PORT}"
