clusterConnections:
  - name: "cluster-b"
    local:
      connectionType: "tcp"
      tcpClient:
        address: "temporal-b:${TEMPORAL_INTERNAL_PORT}"
      tcpServer:
        address: "0.0.0.0:${PROXY_B_INTERNAL_PORT}"
    remote:
      connectionType: "mux-server"
      muxCount: 1
      muxAddressInfo:
        address: "0.0.0.0:${PROXY_MUX_INTERNAL_PORT}"
profiling:
  pprofAddress: "0.0.0.0:${PROXY_PPROF_INTERNAL_PORT}"
metrics:
  prometheus:
    listenAddress: "0.0.0.0:${PROXY_METRICS_INTERNAL_PORT}"
