// Code generated by cmd/tools/genrpcwrappers. DO NOT EDIT.

package common

import (
	svc122 "github.com/temporalio/s2s-proxy/proto/1_22/server/api/adminservice/v1"
	svc "go.temporal.io/server/api/adminservice/v1"
)

// adminConvertTo122 accepts a protobuf type and returns
// the corresponding gogo-based protobuf type from Temporal v1.22.
func adminConvertTo122(vAny any) (Marshaler, bool) {
	switch vAny.(type) {

	case *svc.AddOrUpdateRemoteClusterResponse:
		return &svc122.AddOrUpdateRemoteClusterResponse{}, true
	case *svc.AddOrUpdateRemoteClusterRequest:
		return &svc122.AddOrUpdateRemoteClusterRequest{}, true

	case *svc.AddSearchAttributesResponse:
		return &svc122.AddSearchAttributesResponse{}, true
	case *svc.AddSearchAttributesRequest:
		return &svc122.AddSearchAttributesRequest{}, true

	case *svc.CloseShardResponse:
		return &svc122.CloseShardResponse{}, true
	case *svc.CloseShardRequest:
		return &svc122.CloseShardRequest{}, true

	case *svc.DeleteWorkflowExecutionResponse:
		return &svc122.DeleteWorkflowExecutionResponse{}, true
	case *svc.DeleteWorkflowExecutionRequest:
		return &svc122.DeleteWorkflowExecutionRequest{}, true

	case *svc.DescribeClusterResponse:
		return &svc122.DescribeClusterResponse{}, true
	case *svc.DescribeClusterRequest:
		return &svc122.DescribeClusterRequest{}, true

	case *svc.DescribeHistoryHostResponse:
		return &svc122.DescribeHistoryHostResponse{}, true
	case *svc.DescribeHistoryHostRequest:
		return &svc122.DescribeHistoryHostRequest{}, true

	case *svc.DescribeMutableStateResponse:
		return &svc122.DescribeMutableStateResponse{}, true
	case *svc.DescribeMutableStateRequest:
		return &svc122.DescribeMutableStateRequest{}, true

	case *svc.GetDLQMessagesResponse:
		return &svc122.GetDLQMessagesResponse{}, true
	case *svc.GetDLQMessagesRequest:
		return &svc122.GetDLQMessagesRequest{}, true

	case *svc.GetDLQReplicationMessagesResponse:
		return &svc122.GetDLQReplicationMessagesResponse{}, true
	case *svc.GetDLQReplicationMessagesRequest:
		return &svc122.GetDLQReplicationMessagesRequest{}, true

	case *svc.GetNamespaceResponse:
		return &svc122.GetNamespaceResponse{}, true
	case *svc.GetNamespaceRequest:
		return &svc122.GetNamespaceRequest{}, true

	case *svc.GetNamespaceReplicationMessagesResponse:
		return &svc122.GetNamespaceReplicationMessagesResponse{}, true
	case *svc.GetNamespaceReplicationMessagesRequest:
		return &svc122.GetNamespaceReplicationMessagesRequest{}, true

	case *svc.GetReplicationMessagesResponse:
		return &svc122.GetReplicationMessagesResponse{}, true
	case *svc.GetReplicationMessagesRequest:
		return &svc122.GetReplicationMessagesRequest{}, true

	case *svc.GetSearchAttributesResponse:
		return &svc122.GetSearchAttributesResponse{}, true
	case *svc.GetSearchAttributesRequest:
		return &svc122.GetSearchAttributesRequest{}, true

	case *svc.GetShardResponse:
		return &svc122.GetShardResponse{}, true
	case *svc.GetShardRequest:
		return &svc122.GetShardRequest{}, true

	case *svc.GetTaskQueueTasksResponse:
		return &svc122.GetTaskQueueTasksResponse{}, true
	case *svc.GetTaskQueueTasksRequest:
		return &svc122.GetTaskQueueTasksRequest{}, true

	case *svc.GetWorkflowExecutionRawHistoryV2Response:
		return &svc122.GetWorkflowExecutionRawHistoryV2Response{}, true
	case *svc.GetWorkflowExecutionRawHistoryV2Request:
		return &svc122.GetWorkflowExecutionRawHistoryV2Request{}, true

	case *svc.ListClusterMembersResponse:
		return &svc122.ListClusterMembersResponse{}, true
	case *svc.ListClusterMembersRequest:
		return &svc122.ListClusterMembersRequest{}, true

	case *svc.ListClustersResponse:
		return &svc122.ListClustersResponse{}, true
	case *svc.ListClustersRequest:
		return &svc122.ListClustersRequest{}, true

	case *svc.ListHistoryTasksResponse:
		return &svc122.ListHistoryTasksResponse{}, true
	case *svc.ListHistoryTasksRequest:
		return &svc122.ListHistoryTasksRequest{}, true

	case *svc.MergeDLQMessagesResponse:
		return &svc122.MergeDLQMessagesResponse{}, true
	case *svc.MergeDLQMessagesRequest:
		return &svc122.MergeDLQMessagesRequest{}, true

	case *svc.PurgeDLQMessagesResponse:
		return &svc122.PurgeDLQMessagesResponse{}, true
	case *svc.PurgeDLQMessagesRequest:
		return &svc122.PurgeDLQMessagesRequest{}, true

	case *svc.ReapplyEventsResponse:
		return &svc122.ReapplyEventsResponse{}, true
	case *svc.ReapplyEventsRequest:
		return &svc122.ReapplyEventsRequest{}, true

	case *svc.RebuildMutableStateResponse:
		return &svc122.RebuildMutableStateResponse{}, true
	case *svc.RebuildMutableStateRequest:
		return &svc122.RebuildMutableStateRequest{}, true

	case *svc.RefreshWorkflowTasksResponse:
		return &svc122.RefreshWorkflowTasksResponse{}, true
	case *svc.RefreshWorkflowTasksRequest:
		return &svc122.RefreshWorkflowTasksRequest{}, true

	case *svc.RemoveRemoteClusterResponse:
		return &svc122.RemoveRemoteClusterResponse{}, true
	case *svc.RemoveRemoteClusterRequest:
		return &svc122.RemoveRemoteClusterRequest{}, true

	case *svc.RemoveSearchAttributesResponse:
		return &svc122.RemoveSearchAttributesResponse{}, true
	case *svc.RemoveSearchAttributesRequest:
		return &svc122.RemoveSearchAttributesRequest{}, true

	case *svc.RemoveTaskResponse:
		return &svc122.RemoveTaskResponse{}, true
	case *svc.RemoveTaskRequest:
		return &svc122.RemoveTaskRequest{}, true

	case *svc.ResendReplicationTasksResponse:
		return &svc122.ResendReplicationTasksResponse{}, true
	case *svc.ResendReplicationTasksRequest:
		return &svc122.ResendReplicationTasksRequest{}, true

	case *svc.StreamWorkflowReplicationMessagesResponse:
		return &svc122.StreamWorkflowReplicationMessagesResponse{}, true
	case *svc.StreamWorkflowReplicationMessagesRequest:
		return &svc122.StreamWorkflowReplicationMessagesRequest{}, true
	}
	return nil, false
}
