// Code generated by cmd/tools/genrpcwrappers. DO NOT EDIT.

package common

import (
	svc122 "github.com/temporalio/s2s-proxy/proto/1_22/api/workflowservice/v1"
	svc "go.temporal.io/api/workflowservice/v1"
)

// frontendConvertTo122 accepts a protobuf type and returns
// the corresponding gogo-based protobuf type from Temporal v1.22.
func frontendConvertTo122(vAny any) (Marshaler, bool) {
	switch vAny.(type) {

	case *svc.CountWorkflowExecutionsResponse:
		return &svc122.CountWorkflowExecutionsResponse{}, true
	case *svc.CountWorkflowExecutionsRequest:
		return &svc122.CountWorkflowExecutionsRequest{}, true

	case *svc.CreateScheduleResponse:
		return &svc122.CreateScheduleResponse{}, true
	case *svc.CreateScheduleRequest:
		return &svc122.CreateScheduleRequest{}, true

	case *svc.DeleteScheduleResponse:
		return &svc122.DeleteScheduleResponse{}, true
	case *svc.DeleteScheduleRequest:
		return &svc122.DeleteScheduleRequest{}, true

	case *svc.DeleteWorkflowExecutionResponse:
		return &svc122.DeleteWorkflowExecutionResponse{}, true
	case *svc.DeleteWorkflowExecutionRequest:
		return &svc122.DeleteWorkflowExecutionRequest{}, true

	case *svc.DeprecateNamespaceResponse:
		return &svc122.DeprecateNamespaceResponse{}, true
	case *svc.DeprecateNamespaceRequest:
		return &svc122.DeprecateNamespaceRequest{}, true

	case *svc.DescribeBatchOperationResponse:
		return &svc122.DescribeBatchOperationResponse{}, true
	case *svc.DescribeBatchOperationRequest:
		return &svc122.DescribeBatchOperationRequest{}, true

	case *svc.DescribeNamespaceResponse:
		return &svc122.DescribeNamespaceResponse{}, true
	case *svc.DescribeNamespaceRequest:
		return &svc122.DescribeNamespaceRequest{}, true

	case *svc.DescribeScheduleResponse:
		return &svc122.DescribeScheduleResponse{}, true
	case *svc.DescribeScheduleRequest:
		return &svc122.DescribeScheduleRequest{}, true

	case *svc.DescribeTaskQueueResponse:
		return &svc122.DescribeTaskQueueResponse{}, true
	case *svc.DescribeTaskQueueRequest:
		return &svc122.DescribeTaskQueueRequest{}, true

	case *svc.DescribeWorkflowExecutionResponse:
		return &svc122.DescribeWorkflowExecutionResponse{}, true
	case *svc.DescribeWorkflowExecutionRequest:
		return &svc122.DescribeWorkflowExecutionRequest{}, true

	case *svc.GetClusterInfoResponse:
		return &svc122.GetClusterInfoResponse{}, true
	case *svc.GetClusterInfoRequest:
		return &svc122.GetClusterInfoRequest{}, true

	case *svc.GetSearchAttributesResponse:
		return &svc122.GetSearchAttributesResponse{}, true
	case *svc.GetSearchAttributesRequest:
		return &svc122.GetSearchAttributesRequest{}, true

	case *svc.GetSystemInfoResponse:
		return &svc122.GetSystemInfoResponse{}, true
	case *svc.GetSystemInfoRequest:
		return &svc122.GetSystemInfoRequest{}, true

	case *svc.GetWorkerBuildIdCompatibilityResponse:
		return &svc122.GetWorkerBuildIdCompatibilityResponse{}, true
	case *svc.GetWorkerBuildIdCompatibilityRequest:
		return &svc122.GetWorkerBuildIdCompatibilityRequest{}, true

	case *svc.GetWorkerTaskReachabilityResponse:
		return &svc122.GetWorkerTaskReachabilityResponse{}, true
	case *svc.GetWorkerTaskReachabilityRequest:
		return &svc122.GetWorkerTaskReachabilityRequest{}, true

	case *svc.GetWorkflowExecutionHistoryResponse:
		return &svc122.GetWorkflowExecutionHistoryResponse{}, true
	case *svc.GetWorkflowExecutionHistoryRequest:
		return &svc122.GetWorkflowExecutionHistoryRequest{}, true

	case *svc.GetWorkflowExecutionHistoryReverseResponse:
		return &svc122.GetWorkflowExecutionHistoryReverseResponse{}, true
	case *svc.GetWorkflowExecutionHistoryReverseRequest:
		return &svc122.GetWorkflowExecutionHistoryReverseRequest{}, true

	case *svc.ListArchivedWorkflowExecutionsResponse:
		return &svc122.ListArchivedWorkflowExecutionsResponse{}, true
	case *svc.ListArchivedWorkflowExecutionsRequest:
		return &svc122.ListArchivedWorkflowExecutionsRequest{}, true

	case *svc.ListBatchOperationsResponse:
		return &svc122.ListBatchOperationsResponse{}, true
	case *svc.ListBatchOperationsRequest:
		return &svc122.ListBatchOperationsRequest{}, true

	case *svc.ListClosedWorkflowExecutionsResponse:
		return &svc122.ListClosedWorkflowExecutionsResponse{}, true
	case *svc.ListClosedWorkflowExecutionsRequest:
		return &svc122.ListClosedWorkflowExecutionsRequest{}, true

	case *svc.ListNamespacesResponse:
		return &svc122.ListNamespacesResponse{}, true
	case *svc.ListNamespacesRequest:
		return &svc122.ListNamespacesRequest{}, true

	case *svc.ListOpenWorkflowExecutionsResponse:
		return &svc122.ListOpenWorkflowExecutionsResponse{}, true
	case *svc.ListOpenWorkflowExecutionsRequest:
		return &svc122.ListOpenWorkflowExecutionsRequest{}, true

	case *svc.ListScheduleMatchingTimesResponse:
		return &svc122.ListScheduleMatchingTimesResponse{}, true
	case *svc.ListScheduleMatchingTimesRequest:
		return &svc122.ListScheduleMatchingTimesRequest{}, true

	case *svc.ListSchedulesResponse:
		return &svc122.ListSchedulesResponse{}, true
	case *svc.ListSchedulesRequest:
		return &svc122.ListSchedulesRequest{}, true

	case *svc.ListTaskQueuePartitionsResponse:
		return &svc122.ListTaskQueuePartitionsResponse{}, true
	case *svc.ListTaskQueuePartitionsRequest:
		return &svc122.ListTaskQueuePartitionsRequest{}, true

	case *svc.ListWorkflowExecutionsResponse:
		return &svc122.ListWorkflowExecutionsResponse{}, true
	case *svc.ListWorkflowExecutionsRequest:
		return &svc122.ListWorkflowExecutionsRequest{}, true

	case *svc.PatchScheduleResponse:
		return &svc122.PatchScheduleResponse{}, true
	case *svc.PatchScheduleRequest:
		return &svc122.PatchScheduleRequest{}, true

	case *svc.PollActivityTaskQueueResponse:
		return &svc122.PollActivityTaskQueueResponse{}, true
	case *svc.PollActivityTaskQueueRequest:
		return &svc122.PollActivityTaskQueueRequest{}, true

	case *svc.PollWorkflowExecutionUpdateResponse:
		return &svc122.PollWorkflowExecutionUpdateResponse{}, true
	case *svc.PollWorkflowExecutionUpdateRequest:
		return &svc122.PollWorkflowExecutionUpdateRequest{}, true

	case *svc.PollWorkflowTaskQueueResponse:
		return &svc122.PollWorkflowTaskQueueResponse{}, true
	case *svc.PollWorkflowTaskQueueRequest:
		return &svc122.PollWorkflowTaskQueueRequest{}, true

	case *svc.QueryWorkflowResponse:
		return &svc122.QueryWorkflowResponse{}, true
	case *svc.QueryWorkflowRequest:
		return &svc122.QueryWorkflowRequest{}, true

	case *svc.RecordActivityTaskHeartbeatResponse:
		return &svc122.RecordActivityTaskHeartbeatResponse{}, true
	case *svc.RecordActivityTaskHeartbeatRequest:
		return &svc122.RecordActivityTaskHeartbeatRequest{}, true

	case *svc.RecordActivityTaskHeartbeatByIdResponse:
		return &svc122.RecordActivityTaskHeartbeatByIdResponse{}, true
	case *svc.RecordActivityTaskHeartbeatByIdRequest:
		return &svc122.RecordActivityTaskHeartbeatByIdRequest{}, true

	case *svc.RegisterNamespaceResponse:
		return &svc122.RegisterNamespaceResponse{}, true
	case *svc.RegisterNamespaceRequest:
		return &svc122.RegisterNamespaceRequest{}, true

	case *svc.RequestCancelWorkflowExecutionResponse:
		return &svc122.RequestCancelWorkflowExecutionResponse{}, true
	case *svc.RequestCancelWorkflowExecutionRequest:
		return &svc122.RequestCancelWorkflowExecutionRequest{}, true

	case *svc.ResetStickyTaskQueueResponse:
		return &svc122.ResetStickyTaskQueueResponse{}, true
	case *svc.ResetStickyTaskQueueRequest:
		return &svc122.ResetStickyTaskQueueRequest{}, true

	case *svc.ResetWorkflowExecutionResponse:
		return &svc122.ResetWorkflowExecutionResponse{}, true
	case *svc.ResetWorkflowExecutionRequest:
		return &svc122.ResetWorkflowExecutionRequest{}, true

	case *svc.RespondActivityTaskCanceledResponse:
		return &svc122.RespondActivityTaskCanceledResponse{}, true
	case *svc.RespondActivityTaskCanceledRequest:
		return &svc122.RespondActivityTaskCanceledRequest{}, true

	case *svc.RespondActivityTaskCanceledByIdResponse:
		return &svc122.RespondActivityTaskCanceledByIdResponse{}, true
	case *svc.RespondActivityTaskCanceledByIdRequest:
		return &svc122.RespondActivityTaskCanceledByIdRequest{}, true

	case *svc.RespondActivityTaskCompletedResponse:
		return &svc122.RespondActivityTaskCompletedResponse{}, true
	case *svc.RespondActivityTaskCompletedRequest:
		return &svc122.RespondActivityTaskCompletedRequest{}, true

	case *svc.RespondActivityTaskCompletedByIdResponse:
		return &svc122.RespondActivityTaskCompletedByIdResponse{}, true
	case *svc.RespondActivityTaskCompletedByIdRequest:
		return &svc122.RespondActivityTaskCompletedByIdRequest{}, true

	case *svc.RespondActivityTaskFailedResponse:
		return &svc122.RespondActivityTaskFailedResponse{}, true
	case *svc.RespondActivityTaskFailedRequest:
		return &svc122.RespondActivityTaskFailedRequest{}, true

	case *svc.RespondActivityTaskFailedByIdResponse:
		return &svc122.RespondActivityTaskFailedByIdResponse{}, true
	case *svc.RespondActivityTaskFailedByIdRequest:
		return &svc122.RespondActivityTaskFailedByIdRequest{}, true

	case *svc.RespondQueryTaskCompletedResponse:
		return &svc122.RespondQueryTaskCompletedResponse{}, true
	case *svc.RespondQueryTaskCompletedRequest:
		return &svc122.RespondQueryTaskCompletedRequest{}, true

	case *svc.RespondWorkflowTaskCompletedResponse:
		return &svc122.RespondWorkflowTaskCompletedResponse{}, true
	case *svc.RespondWorkflowTaskCompletedRequest:
		return &svc122.RespondWorkflowTaskCompletedRequest{}, true

	case *svc.RespondWorkflowTaskFailedResponse:
		return &svc122.RespondWorkflowTaskFailedResponse{}, true
	case *svc.RespondWorkflowTaskFailedRequest:
		return &svc122.RespondWorkflowTaskFailedRequest{}, true

	case *svc.ScanWorkflowExecutionsResponse:
		return &svc122.ScanWorkflowExecutionsResponse{}, true
	case *svc.ScanWorkflowExecutionsRequest:
		return &svc122.ScanWorkflowExecutionsRequest{}, true

	case *svc.SignalWithStartWorkflowExecutionResponse:
		return &svc122.SignalWithStartWorkflowExecutionResponse{}, true
	case *svc.SignalWithStartWorkflowExecutionRequest:
		return &svc122.SignalWithStartWorkflowExecutionRequest{}, true

	case *svc.SignalWorkflowExecutionResponse:
		return &svc122.SignalWorkflowExecutionResponse{}, true
	case *svc.SignalWorkflowExecutionRequest:
		return &svc122.SignalWorkflowExecutionRequest{}, true

	case *svc.StartBatchOperationResponse:
		return &svc122.StartBatchOperationResponse{}, true
	case *svc.StartBatchOperationRequest:
		return &svc122.StartBatchOperationRequest{}, true

	case *svc.StartWorkflowExecutionResponse:
		return &svc122.StartWorkflowExecutionResponse{}, true
	case *svc.StartWorkflowExecutionRequest:
		return &svc122.StartWorkflowExecutionRequest{}, true

	case *svc.StopBatchOperationResponse:
		return &svc122.StopBatchOperationResponse{}, true
	case *svc.StopBatchOperationRequest:
		return &svc122.StopBatchOperationRequest{}, true

	case *svc.TerminateWorkflowExecutionResponse:
		return &svc122.TerminateWorkflowExecutionResponse{}, true
	case *svc.TerminateWorkflowExecutionRequest:
		return &svc122.TerminateWorkflowExecutionRequest{}, true

	case *svc.UpdateNamespaceResponse:
		return &svc122.UpdateNamespaceResponse{}, true
	case *svc.UpdateNamespaceRequest:
		return &svc122.UpdateNamespaceRequest{}, true

	case *svc.UpdateScheduleResponse:
		return &svc122.UpdateScheduleResponse{}, true
	case *svc.UpdateScheduleRequest:
		return &svc122.UpdateScheduleRequest{}, true

	case *svc.UpdateWorkerBuildIdCompatibilityResponse:
		return &svc122.UpdateWorkerBuildIdCompatibilityResponse{}, true
	case *svc.UpdateWorkerBuildIdCompatibilityRequest:
		return &svc122.UpdateWorkerBuildIdCompatibilityRequest{}, true

	case *svc.UpdateWorkflowExecutionResponse:
		return &svc122.UpdateWorkflowExecutionResponse{}, true
	case *svc.UpdateWorkflowExecutionRequest:
		return &svc122.UpdateWorkflowExecutionRequest{}, true
	}
	return nil, false
}
